// <auto-generated />
using System;
using DisbotNext.Infrastructures.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DisbotNext.Infrastructures.Sqlite.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20210406113344_add-auto-generate-pk")]
    partial class addautogeneratepk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("DisbotNext.Infrastructures.Sqlite.Models.ChatLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("ChatLogs");
                });

            modelBuilder.Entity("DisbotNext.Infrastructures.Sqlite.Models.Member", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Exp")
                        .HasColumnType("REAL");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("DisbotNext.Infrastructures.Sqlite.Models.ChatLog", b =>
                {
                    b.HasOne("DisbotNext.Infrastructures.Sqlite.Models.Member", "Author")
                        .WithMany("ChatLogs")
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("DisbotNext.Infrastructures.Sqlite.Models.Member", b =>
                {
                    b.Navigation("ChatLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
